<?php

namespace Database\Seeders;

// use Illuminate\Database\Seeder;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

use App\Models\Countries;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        // $registers = [
        //     [ 'abbreviation' => 'AF', 'name' => 'Afganistán'],
        //     [ 'abbreviation' => 'AX', 'name' => 'Islas Gland'],
        //     [ 'abbreviation' => 'AL', 'name' => 'Albania'],
        //     [ 'abbreviation' => 'DE', 'name' => 'Alemania'],
        //     [ 'abbreviation' => 'AD', 'name' => 'Andorra'],
        //     [ 'abbreviation' => 'AO', 'name' => 'Angola'],
        //     [ 'abbreviation' => 'AI', 'name' => 'Anguilla'],
        //     [ 'abbreviation' => 'AQ', 'name' => 'Antártida'],
        //     [ 'abbreviation' => 'AG', 'name' => 'Antigua y Barbuda'],
        //     [ 'abbreviation' => 'AN', 'name' => 'Antillas Holandesas'],
        //     [ 'abbreviation' => 'SA', 'name' => 'Arabia Saudí'],
        //     [ 'abbreviation' => 'DZ', 'name' => 'Argelia'],
        //     [ 'abbreviation' => 'AR', 'name' => 'Argentina'],
        //     [ 'abbreviation' => 'AM', 'name' => 'Armenia'],
        //     [ 'abbreviation' => 'AW', 'name' => 'Aruba'],
        //     [ 'abbreviation' => 'AU', 'name' => 'Australia'],
        //     [ 'abbreviation' => 'AT', 'name' => 'Austria'],
        //     [ 'abbreviation' => 'AZ', 'name' => 'Azerbaiyán'],
        //     [ 'abbreviation' => 'BS', 'name' => 'Bahamas'],
        //     [ 'abbreviation' => 'BH', 'name' => 'Bahréin'],
        //     [ 'abbreviation' => 'BD', 'name' => 'Bangladesh'],
        //     [ 'abbreviation' => 'BB', 'name' => 'Barbados'],
        //     [ 'abbreviation' => 'BY', 'name' => 'Bielorrusia'],
        //     [ 'abbreviation' => 'BE', 'name' => 'Bélgica'],
        //     [ 'abbreviation' => 'BZ', 'name' => 'Belice'],
        //     [ 'abbreviation' => 'BJ', 'name' => 'Benin'],
        //     [ 'abbreviation' => 'BM', 'name' => 'Bermudas'],
        //     [ 'abbreviation' => 'BT', 'name' => 'Bhután'],
        //     [ 'abbreviation' => 'BO', 'name' => 'Bolivia'],
        //     [ 'abbreviation' => 'BA', 'name' => 'Bosnia y Herzegovina'],
        //     [ 'abbreviation' => 'BW', 'name' => 'Botsuana'],
        //     [ 'abbreviation' => 'BV', 'name' => 'Isla Bouvet'],
        //     [ 'abbreviation' => 'BR', 'name' => 'Brasil'],
        //     [ 'abbreviation' => 'BN', 'name' => 'Brunéi'],
        //     [ 'abbreviation' => 'BG', 'name' => 'Bulgaria'],
        //     [ 'abbreviation' => 'BF', 'name' => 'Burkina Faso'],
        //     [ 'abbreviation' => 'BI', 'name' => 'Burundi'],
        //     [ 'abbreviation' => 'CV', 'name' => 'Cabo Verde'],
        //     [ 'abbreviation' => 'KY', 'name' => 'Islas Caimán'],
        //     [ 'abbreviation' => 'KH', 'name' => 'Camboya'],
        //     [ 'abbreviation' => 'CM', 'name' => 'Camerún'],
        //     [ 'abbreviation' => 'CA', 'name' => 'Canadá'],
        //     [ 'abbreviation' => 'CF', 'name' => 'República Centroafricana'],
        //     [ 'abbreviation' => 'TD', 'name' => 'Chad'],
        //     [ 'abbreviation' => 'CZ', 'name' => 'República Checa'],
        //     [ 'abbreviation' => 'CL', 'name' => 'Chile'],
        //     [ 'abbreviation' => 'CN', 'name' => 'China'],
        //     [ 'abbreviation' => 'CY', 'name' => 'Chipre'],
        //     [ 'abbreviation' => 'CX', 'name' => 'Isla de Navidad'],
        //     [ 'abbreviation' => 'VA', 'name' => 'Ciudad del Vaticano'],
        //     [ 'abbreviation' => 'CC', 'name' => 'Islas Cocos'],
        //     [ 'abbreviation' => 'CO', 'name' => 'Colombia'],
        //     [ 'abbreviation' => 'KM', 'name' => 'Comoras'],
        //     [ 'abbreviation' => 'CD', 'name' => 'República Democrática del Congo'],
        //     [ 'abbreviation' => 'CG', 'name' => 'Congo'],
        //     [ 'abbreviation' => 'CK', 'name' => 'Islas Cook'],
        //     [ 'abbreviation' => 'KP', 'name' => 'Corea del Norte'],
        //     [ 'abbreviation' => 'KR', 'name' => 'Corea del Sur'],
        //     [ 'abbreviation' => 'CI', 'name' => 'Costa de Marfil'],
        //     [ 'abbreviation' => 'CR', 'name' => 'Costa Rica'],
        //     [ 'abbreviation' => 'HR', 'name' => 'Croacia'],
        //     [ 'abbreviation' => 'CU', 'name' => 'Cuba'],
        //     [ 'abbreviation' => 'DK', 'name' => 'Dinamarca'],
        //     [ 'abbreviation' => 'DM', 'name' => 'Dominica'],
        //     [ 'abbreviation' => 'DO', 'name' => 'República Dominicana'],
        //     [ 'abbreviation' => 'EC', 'name' => 'Ecuador'],
        //     [ 'abbreviation' => 'EG', 'name' => 'Egipto'],
        //     [ 'abbreviation' => 'SV', 'name' => 'El Salvador'],
        //     [ 'abbreviation' => 'AE', 'name' => 'Emiratos Árabes Unidos'],
        //     [ 'abbreviation' => 'ER', 'name' => 'Eritrea'],
        //     [ 'abbreviation' => 'SK', 'name' => 'Eslovaquia'],
        //     [ 'abbreviation' => 'SI', 'name' => 'Eslovenia'],
        //     [ 'abbreviation' => 'ES', 'name' => 'España'],
        //     [ 'abbreviation' => 'UM', 'name' => 'Islas ultramarinas de Estados Unidos'],
        //     [ 'abbreviation' => 'US', 'name' => 'Estados Unidos'],
        //     [ 'abbreviation' => 'EE', 'name' => 'Estonia'],
        //     [ 'abbreviation' => 'ET', 'name' => 'Etiopía'],
        //     [ 'abbreviation' => 'FO', 'name' => 'Islas Feroe'],
        //     [ 'abbreviation' => 'PH', 'name' => 'Filipinas'],
        //     [ 'abbreviation' => 'FI', 'name' => 'Finlandia'],
        //     [ 'abbreviation' => 'FJ', 'name' => 'Fiyi'],
        //     [ 'abbreviation' => 'FR', 'name' => 'Francia'],
        //     [ 'abbreviation' => 'GA', 'name' => 'Gabón'],
        //     [ 'abbreviation' => 'GM', 'name' => 'Gambia'],
        //     [ 'abbreviation' => 'GE', 'name' => 'Georgia'],
        //     [ 'abbreviation' => 'GS', 'name' => 'Islas Georgias del Sur y Sandwich del Sur'],
        //     [ 'abbreviation' => 'GH', 'name' => 'Ghana'],
        //     [ 'abbreviation' => 'GI', 'name' => 'Gibraltar'],
        //     [ 'abbreviation' => 'GD', 'name' => 'Granada'],
        //     [ 'abbreviation' => 'GR', 'name' => 'Grecia'],
        //     [ 'abbreviation' => 'GL', 'name' => 'Groenlandia'],
        //     [ 'abbreviation' => 'GP', 'name' => 'Guadalupe'],
        //     [ 'abbreviation' => 'GU', 'name' => 'Guam'],
        //     [ 'abbreviation' => 'GT', 'name' => 'Guatemala'],
        //     [ 'abbreviation' => 'GF', 'name' => 'Guayana Francesa'],
        //     [ 'abbreviation' => 'GN', 'name' => 'Guinea'],
        //     [ 'abbreviation' => 'GQ', 'name' => 'Guinea Ecuatorial'],
        //     [ 'abbreviation' => 'GW', 'name' => 'Guinea-Bissau'],
        //     [ 'abbreviation' => 'GY', 'name' => 'Guyana'],
        //     [ 'abbreviation' => 'HT', 'name' => 'Haití'],
        //     [ 'abbreviation' => 'HM', 'name' => 'Islas Heard y McDonald'],
        //     [ 'abbreviation' => 'HN', 'name' => 'Honduras'],
        //     [ 'abbreviation' => 'HK', 'name' => 'Hong Kong'],
        //     [ 'abbreviation' => 'HU', 'name' => 'Hungría'],
        //     [ 'abbreviation' => 'IN', 'name' => 'India'],
        //     [ 'abbreviation' => 'ID', 'name' => 'Indonesia'],
        //     [ 'abbreviation' => 'IR', 'name' => 'Irán'],
        //     [ 'abbreviation' => 'IQ', 'name' => 'Iraq'],
        //     [ 'abbreviation' => 'IE', 'name' => 'Irlanda'],
        //     [ 'abbreviation' => 'IS', 'name' => 'Islandia'],
        //     [ 'abbreviation' => 'IL', 'name' => 'Israel'],
        //     [ 'abbreviation' => 'IT', 'name' => 'Italia'],
        //     [ 'abbreviation' => 'JM', 'name' => 'Jamaica'],
        //     [ 'abbreviation' => 'JP', 'name' => 'Japón'],
        //     [ 'abbreviation' => 'JO', 'name' => 'Jordania'],
        //     [ 'abbreviation' => 'KZ', 'name' => 'Kazajstán'],
        //     [ 'abbreviation' => 'KE', 'name' => 'Kenia'],
        //     [ 'abbreviation' => 'KG', 'name' => 'Kirguistán'],
        //     [ 'abbreviation' => 'KI', 'name' => 'Kiribati'],
        //     [ 'abbreviation' => 'KW', 'name' => 'Kuwait'],
        //     [ 'abbreviation' => 'LA', 'name' => 'Laos'],
        //     [ 'abbreviation' => 'LS', 'name' => 'Lesotho'],
        //     [ 'abbreviation' => 'LV', 'name' => 'Letonia'],
        //     [ 'abbreviation' => 'LB', 'name' => 'Líbano'],
        //     [ 'abbreviation' => 'LR', 'name' => 'Liberia'],
        //     [ 'abbreviation' => 'LY', 'name' => 'Libia'],
        //     [ 'abbreviation' => 'LI', 'name' => 'Liechtenstein'],
        //     [ 'abbreviation' => 'LT', 'name' => 'Lituania'],
        //     [ 'abbreviation' => 'LU', 'name' => 'Luxemburgo'],
        //     [ 'abbreviation' => 'MO', 'name' => 'Macao'],
        //     [ 'abbreviation' => 'MK', 'name' => 'ARY Macedonia'],
        //     [ 'abbreviation' => 'MG', 'name' => 'Madagascar'],
        //     [ 'abbreviation' => 'MY', 'name' => 'Malasia'],
        //     [ 'abbreviation' => 'MW', 'name' => 'Malawi'],
        //     [ 'abbreviation' => 'MV', 'name' => 'Maldivas'],
        //     [ 'abbreviation' => 'ML', 'name' => 'Malí'],
        //     [ 'abbreviation' => 'MT', 'name' => 'Malta'],
        //     [ 'abbreviation' => 'FK', 'name' => 'Islas Malvinas'],
        //     [ 'abbreviation' => 'MP', 'name' => 'Islas Marianas del Norte'],
        //     [ 'abbreviation' => 'MA', 'name' => 'Marruecos'],
        //     [ 'abbreviation' => 'MH', 'name' => 'Islas Marshall'],
        //     [ 'abbreviation' => 'MQ', 'name' => 'Martinica'],
        //     [ 'abbreviation' => 'MU', 'name' => 'Mauricio'],
        //     [ 'abbreviation' => 'MR', 'name' => 'Mauritania'],
        //     [ 'abbreviation' => 'YT', 'name' => 'Mayotte'],
        //     [ 'abbreviation' => 'MX', 'name' => 'México'],
        //     [ 'abbreviation' => 'FM', 'name' => 'Micronesia'],
        //     [ 'abbreviation' => 'MD', 'name' => 'Moldavia'],
        //     [ 'abbreviation' => 'MC', 'name' => 'Mónaco'],
        //     [ 'abbreviation' => 'MN', 'name' => 'Mongolia'],
        //     [ 'abbreviation' => 'MS', 'name' => 'Montserrat'],
        //     [ 'abbreviation' => 'MZ', 'name' => 'Mozambique'],
        //     [ 'abbreviation' => 'MM', 'name' => 'Myanmar'],
        //     [ 'abbreviation' => 'NA', 'name' => 'Namibia'],
        //     [ 'abbreviation' => 'NR', 'name' => 'Nauru'],
        //     [ 'abbreviation' => 'NP', 'name' => 'Nepal'],
        //     [ 'abbreviation' => 'NI', 'name' => 'Nicaragua'],
        //     [ 'abbreviation' => 'NE', 'name' => 'Níger'],
        //     [ 'abbreviation' => 'NG', 'name' => 'Nigeria'],
        //     [ 'abbreviation' => 'NU', 'name' => 'Niue'],
        //     [ 'abbreviation' => 'NF', 'name' => 'Isla Norfolk'],
        //     [ 'abbreviation' => 'NO', 'name' => 'Noruega'],
        //     [ 'abbreviation' => 'NC', 'name' => 'Nueva Caledonia'],
        //     [ 'abbreviation' => 'NZ', 'name' => 'Nueva Zelanda'],
        //     [ 'abbreviation' => 'OM', 'name' => 'Omán'],
        //     [ 'abbreviation' => 'NL', 'name' => 'Países Bajos'],
        //     [ 'abbreviation' => 'PK', 'name' => 'Pakistán'],
        //     [ 'abbreviation' => 'PW', 'name' => 'Palau'],
        //     [ 'abbreviation' => 'PS', 'name' => 'Palestina'],
        //     [ 'abbreviation' => 'PA', 'name' => 'Panamá'],
        //     [ 'abbreviation' => 'PG', 'name' => 'Papúa Nueva Guinea'],
        //     [ 'abbreviation' => 'PY', 'name' => 'Paraguay'],
        //     [ 'abbreviation' => 'PE', 'name' => 'Perú'],
        //     [ 'abbreviation' => 'PN', 'name' => 'Islas Pitcairn'],
        //     [ 'abbreviation' => 'PF', 'name' => 'Polinesia Francesa'],
        //     [ 'abbreviation' => 'PL', 'name' => 'Polonia'],
        //     [ 'abbreviation' => 'PT', 'name' => 'Portugal'],
        //     [ 'abbreviation' => 'PR', 'name' => 'Puerto Rico'],
        //     [ 'abbreviation' => 'QA', 'name' => 'Qatar'],
        //     [ 'abbreviation' => 'GB', 'name' => 'Reino Unido'],
        //     [ 'abbreviation' => 'RE', 'name' => 'Reunión'],
        //     [ 'abbreviation' => 'RW', 'name' => 'Ruanda'],
        //     [ 'abbreviation' => 'RO', 'name' => 'Rumania'],
        //     [ 'abbreviation' => 'RU', 'name' => 'Rusia'],
        //     [ 'abbreviation' => 'EH', 'name' => 'Sahara Occidental'],
        //     [ 'abbreviation' => 'SB', 'name' => 'Islas Salomón'],
        //     [ 'abbreviation' => 'WS', 'name' => 'Samoa'],
        //     [ 'abbreviation' => 'AS', 'name' => 'Samoa Americana'],
        //     [ 'abbreviation' => 'KN', 'name' => 'San Cristóbal y Nevis'],
        //     [ 'abbreviation' => 'SM', 'name' => 'San Marino'],
        //     [ 'abbreviation' => 'PM', 'name' => 'San Pedro y Miquelón'],
        //     [ 'abbreviation' => 'VC', 'name' => 'San Vicente y las Granadinas'],
        //     [ 'abbreviation' => 'SH', 'name' => 'Santa Helena'],
        //     [ 'abbreviation' => 'LC', 'name' => 'Santa Lucía'],
        //     [ 'abbreviation' => 'ST', 'name' => 'Santo Tomé y Príncipe'],
        //     [ 'abbreviation' => 'SN', 'name' => 'Senegal'],
        //     [ 'abbreviation' => 'CS', 'name' => 'Serbia y Montenegro'],
        //     [ 'abbreviation' => 'SC', 'name' => 'Seychelles'],
        //     [ 'abbreviation' => 'SL', 'name' => 'Sierra Leona'],
        //     [ 'abbreviation' => 'SG', 'name' => 'Singapur'],
        //     [ 'abbreviation' => 'SY', 'name' => 'Siria'],
        //     [ 'abbreviation' => 'SO', 'name' => 'Somalia'],
        //     [ 'abbreviation' => 'LK', 'name' => 'Sri Lanka'],
        //     [ 'abbreviation' => 'SZ', 'name' => 'Suazilandia'],
        //     [ 'abbreviation' => 'ZA', 'name' => 'Sudáfrica'],
        //     [ 'abbreviation' => 'SD', 'name' => 'Sudán'],
        //     [ 'abbreviation' => 'SE', 'name' => 'Suecia'],
        //     [ 'abbreviation' => 'CH', 'name' => 'Suiza'],
        //     [ 'abbreviation' => 'SR', 'name' => 'Surinam'],
        //     [ 'abbreviation' => 'SJ', 'name' => 'Svalbard y Jan Mayen'],
        //     [ 'abbreviation' => 'TH', 'name' => 'Tailandia'],
        //     [ 'abbreviation' => 'TW', 'name' => 'Taiwán'],
        //     [ 'abbreviation' => 'TZ', 'name' => 'Tanzania'],
        //     [ 'abbreviation' => 'TJ', 'name' => 'Tayikistán'],
        //     [ 'abbreviation' => 'IO', 'name' => 'Territorio Británico del Océano Índico'],
        //     [ 'abbreviation' => 'TF', 'name' => 'Territorios Australes Franceses'],
        //     [ 'abbreviation' => 'TL', 'name' => 'Timor Oriental'],
        //     [ 'abbreviation' => 'TG', 'name' => 'Togo'],
        //     [ 'abbreviation' => 'TK', 'name' => 'Tokelau'],
        //     [ 'abbreviation' => 'TO', 'name' => 'Tonga'],
        //     [ 'abbreviation' => 'TT', 'name' => 'Trinidad y Tobago'],
        //     [ 'abbreviation' => 'TN', 'name' => 'Túnez'],
        //     [ 'abbreviation' => 'TC', 'name' => 'Islas Turcas y Caicos'],
        //     [ 'abbreviation' => 'TM', 'name' => 'Turkmenistán'],
        //     [ 'abbreviation' => 'TR', 'name' => 'Turquía'],
        //     [ 'abbreviation' => 'TV', 'name' => 'Tuvalu'],
        //     [ 'abbreviation' => 'UA', 'name' => 'Ucrania'],
        //     [ 'abbreviation' => 'UG', 'name' => 'Uganda'],
        //     [ 'abbreviation' => 'UY', 'name' => 'Uruguay'],
        //     [ 'abbreviation' => 'UZ', 'name' => 'Uzbekistán'],
        //     [ 'abbreviation' => 'VU', 'name' => 'Vanuatu'],
        //     [ 'abbreviation' => 'VE', 'name' => 'Venezuela'],
        //     [ 'abbreviation' => 'VN', 'name' => 'Vietnam'],
        //     [ 'abbreviation' => 'VG', 'name' => 'Islas Vírgenes Británicas'],
        //     [ 'abbreviation' => 'VI', 'name' => 'Islas Vírgenes de los Estados Unidos'],
        //     [ 'abbreviation' => 'WF', 'name' => 'Wallis y Futuna'],
        //     [ 'abbreviation' => 'YE', 'name' => 'Yemen'],
        //     [ 'abbreviation' => 'DJ', 'name' => 'Yibuti'],
        //     [ 'abbreviation' => 'ZM', 'name' => 'Zambia'],
        //     [ 'abbreviation' => 'ZW', 'name' => 'Zimbabue']
        // ];
        // // Country::factory()
        // //     ->count(50)
        // //     ->hasPosts(1)
        // //     ->create();
        // foreach ($registers as $register) {
        // // 	DB::table('countries')->insert($register);
        // Countries::create($register);
        // }
        
    }
}
